name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - staging

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: django-cicd-sa-001@ace-course-web-app-489106.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set environment
        run: |
          BRANCH="${GITHUB_REF##*/}"

          if [ "$BRANCH" = "main" ]; then
            echo "SERVICE=django-app-prod" >> $GITHUB_ENV
          else
            echo "SERVICE=django-app-staging" >> $GITHUB_ENV
          fi

      - name: Configure Docker auth
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Image
        run: |
          IMAGE=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.REPOSITORY }}/django-app:${{ github.sha }}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $IMAGE \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
